---

language: python
python:
  - 3.6
services: docker

env:
  global:
    - ROLE_NAME: lxd
  matrix:
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
