---

dist: bionic
addons:
  snaps:
    - lxd

language: python
python:
  - 3.6

env:
  global:
    - ROLE_NAME: lxd
  matrix:
    - MOLECULE_DISTRO_BOX: generic/ubuntu1804

install:
  - sudo add-apt-repository universe && sudo apt update
  - wget https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_x86_64.deb
  - sudo dpkg -i vagrant_2.1.1_x86_64.deb
  - sudo apt install qemu-kvm qemu-utils libvirt-bin libvirt0 libvirt-dev
  - vagrant plugin install vagrant-libvirt
  - pip install molecule docker python-vagrant paramiko
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
