---

- name: prepare facts
  set_fact:
    __lxd_command: "{{ lxd_use_snap_daemon | ternary('/snap/bin/lxd','lxd') }}"

- name: establish packages
  become: true
  package:
    name:
      - lxd
      - lxd-client
    state: "{{ lxd_use_snap_daemon | ternary('absent','present') }}"
  tags: install

- name: establish group
  become: true
  group:
    name: lxd
    system: true
    state: present
  tags: install

- name: establish user in group
  when: ansible_user is defined
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: lxd
    append: true
  tags: install

- name: establish uid mapping
  when: ansible_user_uid is defined
  become: true
  lineinfile:
    path: /etc/subuid
    line: "{{ item }}:{{ ansible_user_uid }}:1"
    state: present
  loop:
    - lxd
    - root

- name: establish gid mapping
  when: ansible_user_gid is defined
  become: true
  lineinfile:
    path: /etc/subgid
    line: "{{ item }}:{{ ansible_user_gid }}:1"
    state: present
  loop:
    - lxd
    - root

- name: establish snap package
  when: lxd_use_snap_daemon | bool
  become: true
  snap:
    name: lxd
    state: present
  tags: install

- name: setup service
  when: ansible_service_mgr == 'systemd'
  become: true
  systemd:
    name: "{{ lxd_use_snap_daemon | ternary('snap.lxd.daemon.service','lxd') }}"
    state: started
    enabled: true
    scope: system
  tags: install

- name: auto-configure daemon
  when: lxd_configuration is not defined
  become: true
  command: "{{ __lxd_command }} init --auto"
  changed_when: false
  tags: configure

- name: configure daemon
  when: lxd_configuration is defined
  become: true
  block:
    - name: read current configuration
      command: "{{ __lxd_command }} init --dump"
      changed_when: false
      register: __used_lxd_configuration

    - name: compare with the desired configuration
      set_fact:
        __desired_configuration: "{{ lxd_configuration | combine({'profiles': []}) }}"
        __current_configuration: "{{ __used_lxd_configuration.stdout | from_yaml | combine({'profiles': []}) }}"

    - name: establish desired configuration
      when: __desired_configuration != __current_configuration
      shell: |
        cat <<EOF | {{ __lxd_command }} init --preseed
        {{ lxd_configuration }}
        EOF
      register: __configuration_seeding
      failed_when: __configuration_seeding.rc != 0
  tags: configure

- name: establish profiles
  become: true
  lxd_profile: "{{ item }}"
  loop: "{{ lxd_profiles }}"
  tags: configure

- name: establish remotes
  become: true
  command: 'lxc remote add --protocol {{ item.protocol }} {{ item.name }} {{ item.url }}'
  register: __insert_remote
  changed_when: __insert_remote.rc == 0
  failed_when: false
  loop: "{{ lxd_remotes }}"
  tags: configure
