---

- name: establish packages
  package:
    name:
      - lxd
      - lxd-client
    state: "{{ 'absent' if use_snap else 'present' }}"

- name: establish group
  group:
    name: lxd
    system: yes
    state: present

- name: establish user in group
  user:
    name: "{{ ansible_user }}"
    groups: lxd
    append: yes

- name: establish snap package
  snap:
    name: lxd
    state: present
  when: use_snap

- name: setup service
  systemd:
    name: snap.lxd.daemon.service 
    state: started
    enabled: yes
    scope: system       

- name: add minimal ubuntu repo
  command: lxc remote add --protocol simplestreams ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/
  register: __insert_minimal_ubuntu
  failed_when: false
  changed_when: __insert_minimal_ubuntu.rc == 0 

- name: read current configuration
  command: lxd init --dump
  changed_when: false
  register: __used_lxd_configuration
  when: configuration is defined 

- name: introduce preseed configuration
  shell: echo {{ configuration }} | lxd init --preseed 
  register: __configuration_seeding
  failed_when: __configuration_seeding.rc != 0 
  when:
    - configuration is defined
    - "configuration != __used_lxd_configuration.stdout | from_yaml"
