---

- name: establish packages
  package:
    name:
      - lxd
      - lxd-client
    state: "{{ 'absent' if use_snap else 'present' }}"
  tags: install

- name: establish group
  group:
    name: lxd
    system: true
    state: present
  tags: install

- name: establish user in group
  user:
    name: "{{ ansible_user }}"
    groups: lxd
    append: true
  tags: install

- name: establish snap package
  when: use_snap | bool
  snap:
    name: lxd
    state: present
  tags: install

- name: setup service
  systemd:
    name: snap.lxd.daemon.service
    state: started
    enabled: true
    scope: system
  tags: install

- name: add minimal ubuntu repo
  command: >-
    lxc remote add --protocol simplestreams
    ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/
  register: __insert_minimal_ubuntu
  failed_when: false
  changed_when: __insert_minimal_ubuntu.rc == 0
  tags: configure

- name: read current configuration
  when: configuration is defined
  become: true
  shell: "{{ '/snap/bin/lxd' if use_snap else 'lxd' }} init --dump"
  args:
    executable: /bin/bash
  changed_when: false
  register: __used_lxd_configuration
  tags: configure

- name: introduce preseed configuration
  when:
    - configuration is defined
    - "configuration != __used_lxd_configuration.stdout | from_yaml"
  become: true
  shell: >-
    echo "{{ configuration }}" |
    {{ '/snap/bin/lxd' if use_snap else 'lxd' }} init --preseed
  args:
    executable: /bin/bash
  register: __configuration_seeding
  failed_when: __configuration_seeding.rc != 0
  tags: configure

- name: establish profiles
  lxd_profile: "{{ item }}"
  loop: "{{ profiles }}"
