---

- name: establish packages
  package:
    name:
      - lxd
      - lxd-client
    state: "{{ use_snap | ternary('absent','present') }}"
  tags: install

- name: establish group
  group:
    name: lxd
    system: true
    state: present
  tags: install

- name: establish user in group
  when: ansible_user is defined
  user:
    name: "{{ ansible_user }}"
    groups: lxd
    append: true
  tags: install

- name: establish snap package
  when: use_snap | bool
  snap:
    name: lxd
    state: present
  tags: install

- name: setup service
  when: ansible_service_mgr == 'systemd'
  systemd:
    name: "{{ use_snap | ternary('snap.lxd.daemon.service','lxd') }}"
    state: started
    enabled: true
    scope: system
  tags: install

- name: add minimal ubuntu repo
  command: >-
    lxc remote add --protocol simplestreams
    ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/
  register: __insert_minimal_ubuntu
  failed_when: false
  changed_when: __insert_minimal_ubuntu.rc == 0
  tags: configure

- name: read current configuration
  when: configuration is defined
  become: true
  command: "{{ use_snap | ternary('/snap/bin/lxd','lxd') }} init --dump"
  changed_when: false
  register: __used_lxd_configuration
  tags: configure

- name: introduce preseed configuration
  when:
    - configuration is defined
    - "configuration != __used_lxd_configuration.stdout | from_yaml"
  become: true
  command: >-
    {{ use_snap | ternary('/snap/bin/lxd','lxd')  }} init --preseed -- {{ configuration }}
  register: __configuration_seeding
  failed_when: __configuration_seeding.rc != 0
  tags: configure

- name: establish profiles
  lxd_profile: "{{ item }}"
  loop: "{{ profiles }}"
