---

- name: Converge
  hosts: all
  roles:
    - role: ansible-role-lxd
      vars:
        lxd_use_snap_daemon: false
        lxd_configuration:
          config:
            images.auto_update_interval: "0"
        lxd_profiles:
          - name: overprivileged
            description: "Way too many limitations removed for a production setup"
            config:
              security.privileged: "true"
              security.nesting: "true"
              raw.lxc: |
                lxc.apparmor.profile=unconfined
                lxc.mount.auto=proc:rw sys:rw
                lxc.cgroup.devices.allow=a *.* rwm
                lxc.cap.drop=
        lxd_remotes:
          - name: ubuntu-minimal
            url: https://cloud-images.ubuntu.com/minimal/releases/
            protocol: simplestreams
